import { generateFicheMissionPdf, generatePassageAVidePdf, generateEdlPapierPdf } from "@/lib/documents-officiels";
const company:any = { raison_sociale:"TRANSPORTS LIGNEO", forme_juridique:"SASU", capital_social:"5 000 €", rcs:"Tours 123", siret:"12345678900019", tva_intra:"FR123", adresse_ligne1:"12 rue de la Gare", adresse_cp:"37000", adresse_ville:"Tours", email_contact:"contact@x.fr", telephone:"07 00 00 00 00", site_web:"transportsligneo.fr", signataire_nom:"M. X", signataire_fonction:"Président", assurance_mention:"AXA n°123" };
const long = "Adresse très longue avenue du Général Leclerc, bâtiment C, 75017 Paris";
const f = await generateFicheMissionPdf({ numero:"LIG-2026-0001", vehicule_marque:"Mercedes", vehicule_modele:"Classe A 200 AMG Line", immatriculation:"AB-123-CD", vin:"WDD1770871J000001", carburant:"Essence", boite:"Auto", enlevement_adresse:long, enlevement_contact:"Morgan Landais 0600000000", enlevement_creneau:"12/08 08:00-10:00", enlevement_instructions:"Demander à l'accueil", livraison_adresse:long, livraison_contact:"Jean Dupont", livraison_creneau:"12/08 17:00", livraison_instructions:"Parking niveau -1", convoyeur_nom:"Paul Martin", convoyeur_tel:"0611111111", notes:"Note ".repeat(60) }, company);
const p = await generatePassageAVidePdf({ numero:"PV-1", convoyeur_nom:"Paul Martin", convoyeur_permis:"123456", convoyeur_siret:"12345678900019", vehicule_type:"VL", vehicule_modele:"Renault Clio", vehicule_immat:"AA-111-BB", motif:"Repositionnement après livraison à Lyon", depart:long, arrivee:long, date_trajet:new Date().toISOString(), heures:"08:00 / 12:00", distance_km:420, mission_ref:"LIG-2026-0001" }, company);
const e = await generateEdlPapierPdf({ numero:"EDL-1", client:"Morgan Landais", societe:"CAT FRANCE", marque_modele:"Mercedes Classe A", immatriculation:"AB-123-CD", vin:"WDD1770871J000001", carburant:"Essence", lieu:long, depart:long, arrivee:long, date_prevue:new Date().toISOString(), convoyeur_nom:"Paul Martin" }, company);
const pages = async (b:Blob) => { const t = await b.text(); return (t.match(/\/Type \/Page[^s]/g)||[]).length; };
console.log("fiche", await pages(f), "pav", await pages(p), "edl", await pages(e));
await Bun.write("/tmp/pdft/fiche.pdf", f); await Bun.write("/tmp/pdft/pav.pdf", p); await Bun.write("/tmp/pdft/edl.pdf", e);
