/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReserverRouteImport } from './routes/reserver'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscriptionConvoyeurRouteImport } from './routes/inscription-convoyeur'
import { Route as InscriptionClientRouteImport } from './routes/inscription-client'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ChoisirCompteRouteImport } from './routes/choisir-compte'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as AttenteValidationRouteImport } from './routes/attente-validation'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedDashboardClientRouteImport } from './routes/_authenticated/dashboard-client'
import { Route as AuthenticatedConvoyeurRouteImport } from './routes/_authenticated/convoyeur'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardClientIndexRouteImport } from './routes/_authenticated/dashboard-client.index'
import { Route as AuthenticatedConvoyeurIndexRouteImport } from './routes/_authenticated/convoyeur.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedDashboardClientProfilRouteImport } from './routes/_authenticated/dashboard-client.profil'
import { Route as AuthenticatedDashboardClientNouvelleReservationRouteImport } from './routes/_authenticated/dashboard-client.nouvelle-reservation'
import { Route as AuthenticatedDashboardClientMissionsRouteImport } from './routes/_authenticated/dashboard-client.missions'
import { Route as AuthenticatedDashboardClientDocumentsRouteImport } from './routes/_authenticated/dashboard-client.documents'
import { Route as AuthenticatedConvoyeurProfilRouteImport } from './routes/_authenticated/convoyeur.profil'
import { Route as AuthenticatedConvoyeurMissionsRouteImport } from './routes/_authenticated/convoyeur.missions'
import { Route as AuthenticatedConvoyeurHistoriqueRouteImport } from './routes/_authenticated/convoyeur.historique'
import { Route as AuthenticatedConvoyeurDocumentsRouteImport } from './routes/_authenticated/convoyeur.documents'
import { Route as AuthenticatedConvoyeurDisponibilitesRouteImport } from './routes/_authenticated/convoyeur.disponibilites'
import { Route as AuthenticatedAdminTrajetsRouteImport } from './routes/_authenticated/admin.trajets'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin.documents'
import { Route as AuthenticatedAdminDevisRouteImport } from './routes/_authenticated/admin.devis'
import { Route as AuthenticatedAdminDemandesRouteImport } from './routes/_authenticated/admin.demandes'
import { Route as AuthenticatedAdminConvoyeursRouteImport } from './routes/_authenticated/admin.convoyeurs'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminAttributionsRouteImport } from './routes/_authenticated/admin.attributions'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedDashboardClientMissionsMissionIdRouteImport } from './routes/_authenticated/dashboard-client.missions.$missionId'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserverRoute = ReserverRouteImport.update({
  id: '/reserver',
  path: '/reserver',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionConvoyeurRoute = InscriptionConvoyeurRouteImport.update({
  id: '/inscription-convoyeur',
  path: '/inscription-convoyeur',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionClientRoute = InscriptionClientRouteImport.update({
  id: '/inscription-client',
  path: '/inscription-client',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoisirCompteRoute = ChoisirCompteRouteImport.update({
  id: '/choisir-compte',
  path: '/choisir-compte',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const AttenteValidationRoute = AttenteValidationRouteImport.update({
  id: '/attente-validation',
  path: '/attente-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardClientRoute =
  AuthenticatedDashboardClientRouteImport.update({
    id: '/dashboard-client',
    path: '/dashboard-client',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConvoyeurRoute = AuthenticatedConvoyeurRouteImport.update({
  id: '/convoyeur',
  path: '/convoyeur',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardClientIndexRoute =
  AuthenticatedDashboardClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardClientRoute,
  } as any)
const AuthenticatedConvoyeurIndexRoute =
  AuthenticatedConvoyeurIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConvoyeurRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardClientProfilRoute =
  AuthenticatedDashboardClientProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedDashboardClientRoute,
  } as any)
const AuthenticatedDashboardClientNouvelleReservationRoute =
  AuthenticatedDashboardClientNouvelleReservationRouteImport.update({
    id: '/nouvelle-reservation',
    path: '/nouvelle-reservation',
    getParentRoute: () => AuthenticatedDashboardClientRoute,
  } as any)
const AuthenticatedDashboardClientMissionsRoute =
  AuthenticatedDashboardClientMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => AuthenticatedDashboardClientRoute,
  } as any)
const AuthenticatedDashboardClientDocumentsRoute =
  AuthenticatedDashboardClientDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedDashboardClientRoute,
  } as any)
const AuthenticatedConvoyeurProfilRoute =
  AuthenticatedConvoyeurProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedConvoyeurRoute,
  } as any)
const AuthenticatedConvoyeurMissionsRoute =
  AuthenticatedConvoyeurMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => AuthenticatedConvoyeurRoute,
  } as any)
const AuthenticatedConvoyeurHistoriqueRoute =
  AuthenticatedConvoyeurHistoriqueRouteImport.update({
    id: '/historique',
    path: '/historique',
    getParentRoute: () => AuthenticatedConvoyeurRoute,
  } as any)
const AuthenticatedConvoyeurDocumentsRoute =
  AuthenticatedConvoyeurDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedConvoyeurRoute,
  } as any)
const AuthenticatedConvoyeurDisponibilitesRoute =
  AuthenticatedConvoyeurDisponibilitesRouteImport.update({
    id: '/disponibilites',
    path: '/disponibilites',
    getParentRoute: () => AuthenticatedConvoyeurRoute,
  } as any)
const AuthenticatedAdminTrajetsRoute =
  AuthenticatedAdminTrajetsRouteImport.update({
    id: '/trajets',
    path: '/trajets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDevisRoute = AuthenticatedAdminDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDemandesRoute =
  AuthenticatedAdminDemandesRouteImport.update({
    id: '/demandes',
    path: '/demandes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConvoyeursRoute =
  AuthenticatedAdminConvoyeursRouteImport.update({
    id: '/convoyeurs',
    path: '/convoyeurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAttributionsRoute =
  AuthenticatedAdminAttributionsRouteImport.update({
    id: '/attributions',
    path: '/attributions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardClientMissionsMissionIdRoute =
  AuthenticatedDashboardClientMissionsMissionIdRouteImport.update({
    id: '/$missionId',
    path: '/$missionId',
    getParentRoute: () => AuthenticatedDashboardClientMissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attente-validation': typeof AttenteValidationRoute
  '/cgv': typeof CgvRoute
  '/choisir-compte': typeof ChoisirCompteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/inscription-client': typeof InscriptionClientRoute
  '/inscription-convoyeur': typeof InscriptionConvoyeurRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reserver': typeof ReserverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/convoyeur': typeof AuthenticatedConvoyeurRouteWithChildren
  '/dashboard-client': typeof AuthenticatedDashboardClientRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/attributions': typeof AuthenticatedAdminAttributionsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/convoyeurs': typeof AuthenticatedAdminConvoyeursRoute
  '/admin/demandes': typeof AuthenticatedAdminDemandesRoute
  '/admin/devis': typeof AuthenticatedAdminDevisRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/trajets': typeof AuthenticatedAdminTrajetsRoute
  '/convoyeur/disponibilites': typeof AuthenticatedConvoyeurDisponibilitesRoute
  '/convoyeur/documents': typeof AuthenticatedConvoyeurDocumentsRoute
  '/convoyeur/historique': typeof AuthenticatedConvoyeurHistoriqueRoute
  '/convoyeur/missions': typeof AuthenticatedConvoyeurMissionsRoute
  '/convoyeur/profil': typeof AuthenticatedConvoyeurProfilRoute
  '/dashboard-client/documents': typeof AuthenticatedDashboardClientDocumentsRoute
  '/dashboard-client/missions': typeof AuthenticatedDashboardClientMissionsRouteWithChildren
  '/dashboard-client/nouvelle-reservation': typeof AuthenticatedDashboardClientNouvelleReservationRoute
  '/dashboard-client/profil': typeof AuthenticatedDashboardClientProfilRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/convoyeur/': typeof AuthenticatedConvoyeurIndexRoute
  '/dashboard-client/': typeof AuthenticatedDashboardClientIndexRoute
  '/dashboard-client/missions/$missionId': typeof AuthenticatedDashboardClientMissionsMissionIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attente-validation': typeof AttenteValidationRoute
  '/cgv': typeof CgvRoute
  '/choisir-compte': typeof ChoisirCompteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/inscription-client': typeof InscriptionClientRoute
  '/inscription-convoyeur': typeof InscriptionConvoyeurRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reserver': typeof ReserverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/attributions': typeof AuthenticatedAdminAttributionsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/convoyeurs': typeof AuthenticatedAdminConvoyeursRoute
  '/admin/demandes': typeof AuthenticatedAdminDemandesRoute
  '/admin/devis': typeof AuthenticatedAdminDevisRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/trajets': typeof AuthenticatedAdminTrajetsRoute
  '/convoyeur/disponibilites': typeof AuthenticatedConvoyeurDisponibilitesRoute
  '/convoyeur/documents': typeof AuthenticatedConvoyeurDocumentsRoute
  '/convoyeur/historique': typeof AuthenticatedConvoyeurHistoriqueRoute
  '/convoyeur/missions': typeof AuthenticatedConvoyeurMissionsRoute
  '/convoyeur/profil': typeof AuthenticatedConvoyeurProfilRoute
  '/dashboard-client/documents': typeof AuthenticatedDashboardClientDocumentsRoute
  '/dashboard-client/missions': typeof AuthenticatedDashboardClientMissionsRouteWithChildren
  '/dashboard-client/nouvelle-reservation': typeof AuthenticatedDashboardClientNouvelleReservationRoute
  '/dashboard-client/profil': typeof AuthenticatedDashboardClientProfilRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/convoyeur': typeof AuthenticatedConvoyeurIndexRoute
  '/dashboard-client': typeof AuthenticatedDashboardClientIndexRoute
  '/dashboard-client/missions/$missionId': typeof AuthenticatedDashboardClientMissionsMissionIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/attente-validation': typeof AttenteValidationRoute
  '/cgv': typeof CgvRoute
  '/choisir-compte': typeof ChoisirCompteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/inscription-client': typeof InscriptionClientRoute
  '/inscription-convoyeur': typeof InscriptionConvoyeurRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reserver': typeof ReserverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/convoyeur': typeof AuthenticatedConvoyeurRouteWithChildren
  '/_authenticated/dashboard-client': typeof AuthenticatedDashboardClientRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/admin/attributions': typeof AuthenticatedAdminAttributionsRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/convoyeurs': typeof AuthenticatedAdminConvoyeursRoute
  '/_authenticated/admin/demandes': typeof AuthenticatedAdminDemandesRoute
  '/_authenticated/admin/devis': typeof AuthenticatedAdminDevisRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/trajets': typeof AuthenticatedAdminTrajetsRoute
  '/_authenticated/convoyeur/disponibilites': typeof AuthenticatedConvoyeurDisponibilitesRoute
  '/_authenticated/convoyeur/documents': typeof AuthenticatedConvoyeurDocumentsRoute
  '/_authenticated/convoyeur/historique': typeof AuthenticatedConvoyeurHistoriqueRoute
  '/_authenticated/convoyeur/missions': typeof AuthenticatedConvoyeurMissionsRoute
  '/_authenticated/convoyeur/profil': typeof AuthenticatedConvoyeurProfilRoute
  '/_authenticated/dashboard-client/documents': typeof AuthenticatedDashboardClientDocumentsRoute
  '/_authenticated/dashboard-client/missions': typeof AuthenticatedDashboardClientMissionsRouteWithChildren
  '/_authenticated/dashboard-client/nouvelle-reservation': typeof AuthenticatedDashboardClientNouvelleReservationRoute
  '/_authenticated/dashboard-client/profil': typeof AuthenticatedDashboardClientProfilRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/convoyeur/': typeof AuthenticatedConvoyeurIndexRoute
  '/_authenticated/dashboard-client/': typeof AuthenticatedDashboardClientIndexRoute
  '/_authenticated/dashboard-client/missions/$missionId': typeof AuthenticatedDashboardClientMissionsMissionIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attente-validation'
    | '/cgv'
    | '/choisir-compte'
    | '/confidentialite'
    | '/inscription-client'
    | '/inscription-convoyeur'
    | '/login'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/reserver'
    | '/reset-password'
    | '/setup'
    | '/unsubscribe'
    | '/admin'
    | '/convoyeur'
    | '/dashboard-client'
    | '/email/unsubscribe'
    | '/admin/attributions'
    | '/admin/clients'
    | '/admin/convoyeurs'
    | '/admin/demandes'
    | '/admin/devis'
    | '/admin/documents'
    | '/admin/trajets'
    | '/convoyeur/disponibilites'
    | '/convoyeur/documents'
    | '/convoyeur/historique'
    | '/convoyeur/missions'
    | '/convoyeur/profil'
    | '/dashboard-client/documents'
    | '/dashboard-client/missions'
    | '/dashboard-client/nouvelle-reservation'
    | '/dashboard-client/profil'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/convoyeur/'
    | '/dashboard-client/'
    | '/dashboard-client/missions/$missionId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attente-validation'
    | '/cgv'
    | '/choisir-compte'
    | '/confidentialite'
    | '/inscription-client'
    | '/inscription-convoyeur'
    | '/login'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/reserver'
    | '/reset-password'
    | '/setup'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/admin/attributions'
    | '/admin/clients'
    | '/admin/convoyeurs'
    | '/admin/demandes'
    | '/admin/devis'
    | '/admin/documents'
    | '/admin/trajets'
    | '/convoyeur/disponibilites'
    | '/convoyeur/documents'
    | '/convoyeur/historique'
    | '/convoyeur/missions'
    | '/convoyeur/profil'
    | '/dashboard-client/documents'
    | '/dashboard-client/missions'
    | '/dashboard-client/nouvelle-reservation'
    | '/dashboard-client/profil'
    | '/lovable/email/suppression'
    | '/admin'
    | '/convoyeur'
    | '/dashboard-client'
    | '/dashboard-client/missions/$missionId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/attente-validation'
    | '/cgv'
    | '/choisir-compte'
    | '/confidentialite'
    | '/inscription-client'
    | '/inscription-convoyeur'
    | '/login'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/reserver'
    | '/reset-password'
    | '/setup'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/convoyeur'
    | '/_authenticated/dashboard-client'
    | '/email/unsubscribe'
    | '/_authenticated/admin/attributions'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/convoyeurs'
    | '/_authenticated/admin/demandes'
    | '/_authenticated/admin/devis'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/trajets'
    | '/_authenticated/convoyeur/disponibilites'
    | '/_authenticated/convoyeur/documents'
    | '/_authenticated/convoyeur/historique'
    | '/_authenticated/convoyeur/missions'
    | '/_authenticated/convoyeur/profil'
    | '/_authenticated/dashboard-client/documents'
    | '/_authenticated/dashboard-client/missions'
    | '/_authenticated/dashboard-client/nouvelle-reservation'
    | '/_authenticated/dashboard-client/profil'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/_authenticated/convoyeur/'
    | '/_authenticated/dashboard-client/'
    | '/_authenticated/dashboard-client/missions/$missionId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AttenteValidationRoute: typeof AttenteValidationRoute
  CgvRoute: typeof CgvRoute
  ChoisirCompteRoute: typeof ChoisirCompteRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  InscriptionClientRoute: typeof InscriptionClientRoute
  InscriptionConvoyeurRoute: typeof InscriptionConvoyeurRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  ReserverRoute: typeof ReserverRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserver': {
      id: '/reserver'
      path: '/reserver'
      fullPath: '/reserver'
      preLoaderRoute: typeof ReserverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-convoyeur': {
      id: '/inscription-convoyeur'
      path: '/inscription-convoyeur'
      fullPath: '/inscription-convoyeur'
      preLoaderRoute: typeof InscriptionConvoyeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-client': {
      id: '/inscription-client'
      path: '/inscription-client'
      fullPath: '/inscription-client'
      preLoaderRoute: typeof InscriptionClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choisir-compte': {
      id: '/choisir-compte'
      path: '/choisir-compte'
      fullPath: '/choisir-compte'
      preLoaderRoute: typeof ChoisirCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attente-validation': {
      id: '/attente-validation'
      path: '/attente-validation'
      fullPath: '/attente-validation'
      preLoaderRoute: typeof AttenteValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard-client': {
      id: '/_authenticated/dashboard-client'
      path: '/dashboard-client'
      fullPath: '/dashboard-client'
      preLoaderRoute: typeof AuthenticatedDashboardClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/convoyeur': {
      id: '/_authenticated/convoyeur'
      path: '/convoyeur'
      fullPath: '/convoyeur'
      preLoaderRoute: typeof AuthenticatedConvoyeurRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard-client/': {
      id: '/_authenticated/dashboard-client/'
      path: '/'
      fullPath: '/dashboard-client/'
      preLoaderRoute: typeof AuthenticatedDashboardClientIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardClientRoute
    }
    '/_authenticated/convoyeur/': {
      id: '/_authenticated/convoyeur/'
      path: '/'
      fullPath: '/convoyeur/'
      preLoaderRoute: typeof AuthenticatedConvoyeurIndexRouteImport
      parentRoute: typeof AuthenticatedConvoyeurRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard-client/profil': {
      id: '/_authenticated/dashboard-client/profil'
      path: '/profil'
      fullPath: '/dashboard-client/profil'
      preLoaderRoute: typeof AuthenticatedDashboardClientProfilRouteImport
      parentRoute: typeof AuthenticatedDashboardClientRoute
    }
    '/_authenticated/dashboard-client/nouvelle-reservation': {
      id: '/_authenticated/dashboard-client/nouvelle-reservation'
      path: '/nouvelle-reservation'
      fullPath: '/dashboard-client/nouvelle-reservation'
      preLoaderRoute: typeof AuthenticatedDashboardClientNouvelleReservationRouteImport
      parentRoute: typeof AuthenticatedDashboardClientRoute
    }
    '/_authenticated/dashboard-client/missions': {
      id: '/_authenticated/dashboard-client/missions'
      path: '/missions'
      fullPath: '/dashboard-client/missions'
      preLoaderRoute: typeof AuthenticatedDashboardClientMissionsRouteImport
      parentRoute: typeof AuthenticatedDashboardClientRoute
    }
    '/_authenticated/dashboard-client/documents': {
      id: '/_authenticated/dashboard-client/documents'
      path: '/documents'
      fullPath: '/dashboard-client/documents'
      preLoaderRoute: typeof AuthenticatedDashboardClientDocumentsRouteImport
      parentRoute: typeof AuthenticatedDashboardClientRoute
    }
    '/_authenticated/convoyeur/profil': {
      id: '/_authenticated/convoyeur/profil'
      path: '/profil'
      fullPath: '/convoyeur/profil'
      preLoaderRoute: typeof AuthenticatedConvoyeurProfilRouteImport
      parentRoute: typeof AuthenticatedConvoyeurRoute
    }
    '/_authenticated/convoyeur/missions': {
      id: '/_authenticated/convoyeur/missions'
      path: '/missions'
      fullPath: '/convoyeur/missions'
      preLoaderRoute: typeof AuthenticatedConvoyeurMissionsRouteImport
      parentRoute: typeof AuthenticatedConvoyeurRoute
    }
    '/_authenticated/convoyeur/historique': {
      id: '/_authenticated/convoyeur/historique'
      path: '/historique'
      fullPath: '/convoyeur/historique'
      preLoaderRoute: typeof AuthenticatedConvoyeurHistoriqueRouteImport
      parentRoute: typeof AuthenticatedConvoyeurRoute
    }
    '/_authenticated/convoyeur/documents': {
      id: '/_authenticated/convoyeur/documents'
      path: '/documents'
      fullPath: '/convoyeur/documents'
      preLoaderRoute: typeof AuthenticatedConvoyeurDocumentsRouteImport
      parentRoute: typeof AuthenticatedConvoyeurRoute
    }
    '/_authenticated/convoyeur/disponibilites': {
      id: '/_authenticated/convoyeur/disponibilites'
      path: '/disponibilites'
      fullPath: '/convoyeur/disponibilites'
      preLoaderRoute: typeof AuthenticatedConvoyeurDisponibilitesRouteImport
      parentRoute: typeof AuthenticatedConvoyeurRoute
    }
    '/_authenticated/admin/trajets': {
      id: '/_authenticated/admin/trajets'
      path: '/trajets'
      fullPath: '/admin/trajets'
      preLoaderRoute: typeof AuthenticatedAdminTrajetsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/devis': {
      id: '/_authenticated/admin/devis'
      path: '/devis'
      fullPath: '/admin/devis'
      preLoaderRoute: typeof AuthenticatedAdminDevisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/demandes': {
      id: '/_authenticated/admin/demandes'
      path: '/demandes'
      fullPath: '/admin/demandes'
      preLoaderRoute: typeof AuthenticatedAdminDemandesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/convoyeurs': {
      id: '/_authenticated/admin/convoyeurs'
      path: '/convoyeurs'
      fullPath: '/admin/convoyeurs'
      preLoaderRoute: typeof AuthenticatedAdminConvoyeursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/attributions': {
      id: '/_authenticated/admin/attributions'
      path: '/attributions'
      fullPath: '/admin/attributions'
      preLoaderRoute: typeof AuthenticatedAdminAttributionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard-client/missions/$missionId': {
      id: '/_authenticated/dashboard-client/missions/$missionId'
      path: '/$missionId'
      fullPath: '/dashboard-client/missions/$missionId'
      preLoaderRoute: typeof AuthenticatedDashboardClientMissionsMissionIdRouteImport
      parentRoute: typeof AuthenticatedDashboardClientMissionsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAttributionsRoute: typeof AuthenticatedAdminAttributionsRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminConvoyeursRoute: typeof AuthenticatedAdminConvoyeursRoute
  AuthenticatedAdminDemandesRoute: typeof AuthenticatedAdminDemandesRoute
  AuthenticatedAdminDevisRoute: typeof AuthenticatedAdminDevisRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminTrajetsRoute: typeof AuthenticatedAdminTrajetsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAttributionsRoute: AuthenticatedAdminAttributionsRoute,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminConvoyeursRoute: AuthenticatedAdminConvoyeursRoute,
  AuthenticatedAdminDemandesRoute: AuthenticatedAdminDemandesRoute,
  AuthenticatedAdminDevisRoute: AuthenticatedAdminDevisRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminTrajetsRoute: AuthenticatedAdminTrajetsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedConvoyeurRouteChildren {
  AuthenticatedConvoyeurDisponibilitesRoute: typeof AuthenticatedConvoyeurDisponibilitesRoute
  AuthenticatedConvoyeurDocumentsRoute: typeof AuthenticatedConvoyeurDocumentsRoute
  AuthenticatedConvoyeurHistoriqueRoute: typeof AuthenticatedConvoyeurHistoriqueRoute
  AuthenticatedConvoyeurMissionsRoute: typeof AuthenticatedConvoyeurMissionsRoute
  AuthenticatedConvoyeurProfilRoute: typeof AuthenticatedConvoyeurProfilRoute
  AuthenticatedConvoyeurIndexRoute: typeof AuthenticatedConvoyeurIndexRoute
}

const AuthenticatedConvoyeurRouteChildren: AuthenticatedConvoyeurRouteChildren =
  {
    AuthenticatedConvoyeurDisponibilitesRoute:
      AuthenticatedConvoyeurDisponibilitesRoute,
    AuthenticatedConvoyeurDocumentsRoute: AuthenticatedConvoyeurDocumentsRoute,
    AuthenticatedConvoyeurHistoriqueRoute:
      AuthenticatedConvoyeurHistoriqueRoute,
    AuthenticatedConvoyeurMissionsRoute: AuthenticatedConvoyeurMissionsRoute,
    AuthenticatedConvoyeurProfilRoute: AuthenticatedConvoyeurProfilRoute,
    AuthenticatedConvoyeurIndexRoute: AuthenticatedConvoyeurIndexRoute,
  }

const AuthenticatedConvoyeurRouteWithChildren =
  AuthenticatedConvoyeurRoute._addFileChildren(
    AuthenticatedConvoyeurRouteChildren,
  )

interface AuthenticatedDashboardClientMissionsRouteChildren {
  AuthenticatedDashboardClientMissionsMissionIdRoute: typeof AuthenticatedDashboardClientMissionsMissionIdRoute
}

const AuthenticatedDashboardClientMissionsRouteChildren: AuthenticatedDashboardClientMissionsRouteChildren =
  {
    AuthenticatedDashboardClientMissionsMissionIdRoute:
      AuthenticatedDashboardClientMissionsMissionIdRoute,
  }

const AuthenticatedDashboardClientMissionsRouteWithChildren =
  AuthenticatedDashboardClientMissionsRoute._addFileChildren(
    AuthenticatedDashboardClientMissionsRouteChildren,
  )

interface AuthenticatedDashboardClientRouteChildren {
  AuthenticatedDashboardClientDocumentsRoute: typeof AuthenticatedDashboardClientDocumentsRoute
  AuthenticatedDashboardClientMissionsRoute: typeof AuthenticatedDashboardClientMissionsRouteWithChildren
  AuthenticatedDashboardClientNouvelleReservationRoute: typeof AuthenticatedDashboardClientNouvelleReservationRoute
  AuthenticatedDashboardClientProfilRoute: typeof AuthenticatedDashboardClientProfilRoute
  AuthenticatedDashboardClientIndexRoute: typeof AuthenticatedDashboardClientIndexRoute
}

const AuthenticatedDashboardClientRouteChildren: AuthenticatedDashboardClientRouteChildren =
  {
    AuthenticatedDashboardClientDocumentsRoute:
      AuthenticatedDashboardClientDocumentsRoute,
    AuthenticatedDashboardClientMissionsRoute:
      AuthenticatedDashboardClientMissionsRouteWithChildren,
    AuthenticatedDashboardClientNouvelleReservationRoute:
      AuthenticatedDashboardClientNouvelleReservationRoute,
    AuthenticatedDashboardClientProfilRoute:
      AuthenticatedDashboardClientProfilRoute,
    AuthenticatedDashboardClientIndexRoute:
      AuthenticatedDashboardClientIndexRoute,
  }

const AuthenticatedDashboardClientRouteWithChildren =
  AuthenticatedDashboardClientRoute._addFileChildren(
    AuthenticatedDashboardClientRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedConvoyeurRoute: typeof AuthenticatedConvoyeurRouteWithChildren
  AuthenticatedDashboardClientRoute: typeof AuthenticatedDashboardClientRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedConvoyeurRoute: AuthenticatedConvoyeurRouteWithChildren,
  AuthenticatedDashboardClientRoute:
    AuthenticatedDashboardClientRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AttenteValidationRoute: AttenteValidationRoute,
  CgvRoute: CgvRoute,
  ChoisirCompteRoute: ChoisirCompteRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  InscriptionClientRoute: InscriptionClientRoute,
  InscriptionConvoyeurRoute: InscriptionConvoyeurRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  ReserverRoute: ReserverRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
