/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscriptionConvoyeurRouteImport } from './routes/inscription-convoyeur'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedConvoyeurRouteImport } from './routes/_authenticated/convoyeur'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedConvoyeurIndexRouteImport } from './routes/_authenticated/convoyeur.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedConvoyeurMissionsRouteImport } from './routes/_authenticated/convoyeur.missions'
import { Route as AuthenticatedConvoyeurHistoriqueRouteImport } from './routes/_authenticated/convoyeur.historique'
import { Route as AuthenticatedConvoyeurDocumentsRouteImport } from './routes/_authenticated/convoyeur.documents'
import { Route as AuthenticatedAdminTrajetsRouteImport } from './routes/_authenticated/admin.trajets'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin.documents'
import { Route as AuthenticatedAdminDevisRouteImport } from './routes/_authenticated/admin.devis'
import { Route as AuthenticatedAdminDemandesRouteImport } from './routes/_authenticated/admin.demandes'
import { Route as AuthenticatedAdminConvoyeursRouteImport } from './routes/_authenticated/admin.convoyeurs'
import { Route as AuthenticatedAdminAttributionsRouteImport } from './routes/_authenticated/admin.attributions'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionConvoyeurRoute = InscriptionConvoyeurRouteImport.update({
  id: '/inscription-convoyeur',
  path: '/inscription-convoyeur',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConvoyeurRoute = AuthenticatedConvoyeurRouteImport.update({
  id: '/convoyeur',
  path: '/convoyeur',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConvoyeurIndexRoute =
  AuthenticatedConvoyeurIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConvoyeurRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConvoyeurMissionsRoute =
  AuthenticatedConvoyeurMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => AuthenticatedConvoyeurRoute,
  } as any)
const AuthenticatedConvoyeurHistoriqueRoute =
  AuthenticatedConvoyeurHistoriqueRouteImport.update({
    id: '/historique',
    path: '/historique',
    getParentRoute: () => AuthenticatedConvoyeurRoute,
  } as any)
const AuthenticatedConvoyeurDocumentsRoute =
  AuthenticatedConvoyeurDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedConvoyeurRoute,
  } as any)
const AuthenticatedAdminTrajetsRoute =
  AuthenticatedAdminTrajetsRouteImport.update({
    id: '/trajets',
    path: '/trajets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDevisRoute = AuthenticatedAdminDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDemandesRoute =
  AuthenticatedAdminDemandesRouteImport.update({
    id: '/demandes',
    path: '/demandes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConvoyeursRoute =
  AuthenticatedAdminConvoyeursRouteImport.update({
    id: '/convoyeurs',
    path: '/convoyeurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAttributionsRoute =
  AuthenticatedAdminAttributionsRouteImport.update({
    id: '/attributions',
    path: '/attributions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/inscription-convoyeur': typeof InscriptionConvoyeurRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/setup': typeof SetupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/convoyeur': typeof AuthenticatedConvoyeurRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/attributions': typeof AuthenticatedAdminAttributionsRoute
  '/admin/convoyeurs': typeof AuthenticatedAdminConvoyeursRoute
  '/admin/demandes': typeof AuthenticatedAdminDemandesRoute
  '/admin/devis': typeof AuthenticatedAdminDevisRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/trajets': typeof AuthenticatedAdminTrajetsRoute
  '/convoyeur/documents': typeof AuthenticatedConvoyeurDocumentsRoute
  '/convoyeur/historique': typeof AuthenticatedConvoyeurHistoriqueRoute
  '/convoyeur/missions': typeof AuthenticatedConvoyeurMissionsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/convoyeur/': typeof AuthenticatedConvoyeurIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/inscription-convoyeur': typeof InscriptionConvoyeurRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/setup': typeof SetupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/attributions': typeof AuthenticatedAdminAttributionsRoute
  '/admin/convoyeurs': typeof AuthenticatedAdminConvoyeursRoute
  '/admin/demandes': typeof AuthenticatedAdminDemandesRoute
  '/admin/devis': typeof AuthenticatedAdminDevisRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/trajets': typeof AuthenticatedAdminTrajetsRoute
  '/convoyeur/documents': typeof AuthenticatedConvoyeurDocumentsRoute
  '/convoyeur/historique': typeof AuthenticatedConvoyeurHistoriqueRoute
  '/convoyeur/missions': typeof AuthenticatedConvoyeurMissionsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/convoyeur': typeof AuthenticatedConvoyeurIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/inscription-convoyeur': typeof InscriptionConvoyeurRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/setup': typeof SetupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/convoyeur': typeof AuthenticatedConvoyeurRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/admin/attributions': typeof AuthenticatedAdminAttributionsRoute
  '/_authenticated/admin/convoyeurs': typeof AuthenticatedAdminConvoyeursRoute
  '/_authenticated/admin/demandes': typeof AuthenticatedAdminDemandesRoute
  '/_authenticated/admin/devis': typeof AuthenticatedAdminDevisRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/trajets': typeof AuthenticatedAdminTrajetsRoute
  '/_authenticated/convoyeur/documents': typeof AuthenticatedConvoyeurDocumentsRoute
  '/_authenticated/convoyeur/historique': typeof AuthenticatedConvoyeurHistoriqueRoute
  '/_authenticated/convoyeur/missions': typeof AuthenticatedConvoyeurMissionsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/convoyeur/': typeof AuthenticatedConvoyeurIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgv'
    | '/confidentialite'
    | '/inscription-convoyeur'
    | '/login'
    | '/mentions-legales'
    | '/setup'
    | '/unsubscribe'
    | '/admin'
    | '/convoyeur'
    | '/email/unsubscribe'
    | '/admin/attributions'
    | '/admin/convoyeurs'
    | '/admin/demandes'
    | '/admin/devis'
    | '/admin/documents'
    | '/admin/trajets'
    | '/convoyeur/documents'
    | '/convoyeur/historique'
    | '/convoyeur/missions'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/convoyeur/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgv'
    | '/confidentialite'
    | '/inscription-convoyeur'
    | '/login'
    | '/mentions-legales'
    | '/setup'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/admin/attributions'
    | '/admin/convoyeurs'
    | '/admin/demandes'
    | '/admin/devis'
    | '/admin/documents'
    | '/admin/trajets'
    | '/convoyeur/documents'
    | '/convoyeur/historique'
    | '/convoyeur/missions'
    | '/lovable/email/suppression'
    | '/admin'
    | '/convoyeur'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cgv'
    | '/confidentialite'
    | '/inscription-convoyeur'
    | '/login'
    | '/mentions-legales'
    | '/setup'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/convoyeur'
    | '/email/unsubscribe'
    | '/_authenticated/admin/attributions'
    | '/_authenticated/admin/convoyeurs'
    | '/_authenticated/admin/demandes'
    | '/_authenticated/admin/devis'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/trajets'
    | '/_authenticated/convoyeur/documents'
    | '/_authenticated/convoyeur/historique'
    | '/_authenticated/convoyeur/missions'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/_authenticated/convoyeur/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CgvRoute: typeof CgvRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  InscriptionConvoyeurRoute: typeof InscriptionConvoyeurRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  SetupRoute: typeof SetupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-convoyeur': {
      id: '/inscription-convoyeur'
      path: '/inscription-convoyeur'
      fullPath: '/inscription-convoyeur'
      preLoaderRoute: typeof InscriptionConvoyeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/convoyeur': {
      id: '/_authenticated/convoyeur'
      path: '/convoyeur'
      fullPath: '/convoyeur'
      preLoaderRoute: typeof AuthenticatedConvoyeurRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/convoyeur/': {
      id: '/_authenticated/convoyeur/'
      path: '/'
      fullPath: '/convoyeur/'
      preLoaderRoute: typeof AuthenticatedConvoyeurIndexRouteImport
      parentRoute: typeof AuthenticatedConvoyeurRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/convoyeur/missions': {
      id: '/_authenticated/convoyeur/missions'
      path: '/missions'
      fullPath: '/convoyeur/missions'
      preLoaderRoute: typeof AuthenticatedConvoyeurMissionsRouteImport
      parentRoute: typeof AuthenticatedConvoyeurRoute
    }
    '/_authenticated/convoyeur/historique': {
      id: '/_authenticated/convoyeur/historique'
      path: '/historique'
      fullPath: '/convoyeur/historique'
      preLoaderRoute: typeof AuthenticatedConvoyeurHistoriqueRouteImport
      parentRoute: typeof AuthenticatedConvoyeurRoute
    }
    '/_authenticated/convoyeur/documents': {
      id: '/_authenticated/convoyeur/documents'
      path: '/documents'
      fullPath: '/convoyeur/documents'
      preLoaderRoute: typeof AuthenticatedConvoyeurDocumentsRouteImport
      parentRoute: typeof AuthenticatedConvoyeurRoute
    }
    '/_authenticated/admin/trajets': {
      id: '/_authenticated/admin/trajets'
      path: '/trajets'
      fullPath: '/admin/trajets'
      preLoaderRoute: typeof AuthenticatedAdminTrajetsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/devis': {
      id: '/_authenticated/admin/devis'
      path: '/devis'
      fullPath: '/admin/devis'
      preLoaderRoute: typeof AuthenticatedAdminDevisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/demandes': {
      id: '/_authenticated/admin/demandes'
      path: '/demandes'
      fullPath: '/admin/demandes'
      preLoaderRoute: typeof AuthenticatedAdminDemandesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/convoyeurs': {
      id: '/_authenticated/admin/convoyeurs'
      path: '/convoyeurs'
      fullPath: '/admin/convoyeurs'
      preLoaderRoute: typeof AuthenticatedAdminConvoyeursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/attributions': {
      id: '/_authenticated/admin/attributions'
      path: '/attributions'
      fullPath: '/admin/attributions'
      preLoaderRoute: typeof AuthenticatedAdminAttributionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAttributionsRoute: typeof AuthenticatedAdminAttributionsRoute
  AuthenticatedAdminConvoyeursRoute: typeof AuthenticatedAdminConvoyeursRoute
  AuthenticatedAdminDemandesRoute: typeof AuthenticatedAdminDemandesRoute
  AuthenticatedAdminDevisRoute: typeof AuthenticatedAdminDevisRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminTrajetsRoute: typeof AuthenticatedAdminTrajetsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAttributionsRoute: AuthenticatedAdminAttributionsRoute,
  AuthenticatedAdminConvoyeursRoute: AuthenticatedAdminConvoyeursRoute,
  AuthenticatedAdminDemandesRoute: AuthenticatedAdminDemandesRoute,
  AuthenticatedAdminDevisRoute: AuthenticatedAdminDevisRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminTrajetsRoute: AuthenticatedAdminTrajetsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedConvoyeurRouteChildren {
  AuthenticatedConvoyeurDocumentsRoute: typeof AuthenticatedConvoyeurDocumentsRoute
  AuthenticatedConvoyeurHistoriqueRoute: typeof AuthenticatedConvoyeurHistoriqueRoute
  AuthenticatedConvoyeurMissionsRoute: typeof AuthenticatedConvoyeurMissionsRoute
  AuthenticatedConvoyeurIndexRoute: typeof AuthenticatedConvoyeurIndexRoute
}

const AuthenticatedConvoyeurRouteChildren: AuthenticatedConvoyeurRouteChildren =
  {
    AuthenticatedConvoyeurDocumentsRoute: AuthenticatedConvoyeurDocumentsRoute,
    AuthenticatedConvoyeurHistoriqueRoute:
      AuthenticatedConvoyeurHistoriqueRoute,
    AuthenticatedConvoyeurMissionsRoute: AuthenticatedConvoyeurMissionsRoute,
    AuthenticatedConvoyeurIndexRoute: AuthenticatedConvoyeurIndexRoute,
  }

const AuthenticatedConvoyeurRouteWithChildren =
  AuthenticatedConvoyeurRoute._addFileChildren(
    AuthenticatedConvoyeurRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedConvoyeurRoute: typeof AuthenticatedConvoyeurRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedConvoyeurRoute: AuthenticatedConvoyeurRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CgvRoute: CgvRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  InscriptionConvoyeurRoute: InscriptionConvoyeurRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  SetupRoute: SetupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
