UPDATE public.formation_exams
SET question_count = 10,
    question_pool = '[
      {"question":"Vous arrivez sur le lieu de prise en charge d''un véhicule. Quelle est la première action professionnelle à effectuer ?","choices":["Démarrer le véhicule et vérifier qu''il fonctionne.","Faire un état des lieux complet du véhicule avant tout déplacement.","Ranger immédiatement vos affaires dans le coffre.","Partir rapidement pour respecter l''horaire."],"answer":1,"explanation":"L''état des lieux avant départ est obligatoire. Il permet de protéger le client, le convoyeur et Transports Ligneo en cas de contestation concernant l''état du véhicule."},
      {"question":"Lors de la récupération d''un véhicule, vous constatez une rayure importante qui n''apparaît pas dans le dossier de mission. Que faites-vous ?","choices":["Vous partez car le dommage était déjà présent.","Vous prenez des photos et signalez l''anomalie avant le départ.","Vous demandez au client de réparer immédiatement.","Vous ignorez le problème."],"answer":1,"explanation":"Toute anomalie constatée doit être signalée et documentée avant le départ afin d''éviter tout litige."},
      {"question":"Pendant une mission, le véhicule confié est sous la responsabilité :","choices":["Du propriétaire uniquement.","Du constructeur du véhicule.","Du convoyeur et de Transports Ligneo pendant la mission.","Du client qui attend la livraison."],"answer":2,"explanation":"Le convoyeur devient responsable du bon usage du véhicule dès sa prise en charge jusqu''à sa restitution."},
      {"question":"Un convoyeur utilise un véhicule client pour effectuer un détour personnel de quelques kilomètres. Est-ce acceptable ?","choices":["Oui, si le détour est court.","Oui, si le véhicule fonctionne correctement.","Non, un véhicule client doit être utilisé uniquement dans le cadre de la mission.","Oui, si personne ne le remarque."],"answer":2,"explanation":"Un véhicule confié dans le cadre d''un convoyage ne doit jamais être utilisé à titre personnel."},
      {"question":"Quelle conduite est attendue lors d''un convoyage ?","choices":["Une conduite rapide pour réduire le temps de mission.","Une conduite souple, anticipative et adaptée au véhicule.","Une conduite permettant de tester les performances du véhicule.","Une conduite identique à celle d''un véhicule personnel."],"answer":1,"explanation":"Le convoyeur doit préserver le véhicule confié et limiter les risques de dégradation."},
      {"question":"Un voyant moteur apparaît pendant le trajet. Quelle est la bonne réaction ?","choices":["Continuer jusqu''à destination sans prévenir personne.","Effacer le voyant soi-même.","Sécuriser la situation et contacter Transports Ligneo selon la procédure.","Abandonner immédiatement le véhicule."],"answer":2,"explanation":"Toute anomalie technique doit être signalée afin d''éviter une aggravation du problème."},
      {"question":"Vous êtes bloqué dans un embouteillage important et vous risquez d''être en retard.","choices":["Vous ne dites rien.","Vous informez rapidement Transports Ligneo avec une estimation réaliste.","Vous augmentez votre vitesse pour rattraper le retard.","Vous annulez la mission."],"answer":1,"explanation":"Une communication rapide permet de maintenir la qualité de service et d''organiser les actions nécessaires."},
      {"question":"Vous êtes impliqué dans un accident avec un véhicule client. Quelle est votre priorité ?","choices":["Quitter rapidement les lieux.","Continuer la mission si le véhicule roule encore.","Sécuriser les personnes, appliquer la procédure et informer Transports Ligneo.","Réparer vous-même le véhicule."],"answer":2,"explanation":"La sécurité des personnes est prioritaire. L''incident doit ensuite être déclaré selon les procédures prévues."},
      {"question":"Lors de la livraison d''un véhicule, il faut :","choices":["Donner uniquement les clés.","Vérifier l''état final, transmettre les informations nécessaires et confirmer la restitution.","Partir immédiatement après avoir garé le véhicule.","Éviter tout échange avec le réceptionnaire."],"answer":1,"explanation":"La restitution est une étape essentielle qui garantit la traçabilité et la satisfaction client."},
      {"question":"Pourquoi le comportement du convoyeur est-il important ?","choices":["Parce qu''il représente directement Transports Ligneo auprès des clients.","Parce qu''il peut modifier les conditions de la mission.","Parce qu''il remplace le service commercial.","Parce qu''il décide des tarifs."],"answer":0,"explanation":"Le convoyeur est le représentant terrain de l''entreprise. Son comportement influence directement la confiance des clients."}
    ]'::jsonb,
    updated_at = now()
WHERE is_active = true;